### ISSUE TITLE
Parsing Configuration Error

### ISSUE THREAD

**Issue by mikeshort10** [APSPhysics/eslint-config#18]
## Issue

Currently, installing the config with the latest ESLint and the default configuration results in an error. Additional configuration is required to get the linter working again. If we can address this at the configuration level, that would be ideal. Otherwise, we need to update the documentation to include the solution below.

## Error Message

```
Error: You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

Current ESLint Version: 8.56.0

## Solution

The following configuration needs to be listed at the root of the eslint json:

```yaml
parser: "@typescript-eslint/parser"
parserOptions: 
  project: 
    - ./tsconfig.json
```
